"""Added is_processed to ArticleModel

Revision ID: 05c58418d14d
Revises: b3b4e8a8c30b
Create Date: 2023-11-11 15:28:13.450816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05c58418d14d'
down_revision = 'b3b4e8a8c30b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_processed', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_column('is_processed')

    # ### end Alembic commands ###
