"""empty message

Revision ID: 6484d0bd30f1
Revises: cb2f33265356
Create Date: 2023-11-16 16:14:13.243728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6484d0bd30f1'
down_revision = 'cb2f33265356'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_paragraphs', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_column('has_paragraphs')

    # ### end Alembic commands ###
