"""Added has_embedding to ArticleModel

Revision ID: cb2f33265356
Revises: d8b651d03caf
Create Date: 2023-11-12 14:28:12.746127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb2f33265356'
down_revision = 'd8b651d03caf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_embedding', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_column('has_embedding')

    # ### end Alembic commands ###
